### ISSUE TITLE
Loom Analog Bug

### ISSUE THREAD

**Issue by osuwalkera6** [OPEnSLab-OSU/OPEnS-Lab-Home#1]
When I upload my code to my LoRa Feather M0, I am receiving an "[Device] deserializeJson() failed: InvalidInput" error, even when using default values. I tried inputting values for each element in the array instead and still received the same error.

Here is my json config.h:
"{\
	'general':\
	{\
		'name':'Device',\
		'instance':1,\
		'interval':500\
	},\
	'components':[\
    {\
    'name':'MAX31856',\
    'params':'default'\
    },\
    {\
    'name':'Analog',\
    'params':[\
    8,\
    12,\
    false,\
    false,\
    true,\
    false,\
    false,\
    false,\
    Conversion::NONE,\
    Conversion::NONE,\
    4,\
    Conversion::NONE,\
    Conversion::NONE,\
    Conversion::NONE,\
    25.0]\
    }\
  ]\
}"

One thing I noticed was there is a difference of the number of elements within the config array for the current Analog module vs. those of the past, such as those used in the SmartRock or Stroud projects. Thank you for your help!

**Comment by prototypicalpro** [comment]
You'll want to create an issue on the Loom repository: https://github.com/OPEnSLab-OSU/Loom/issues instead of this repository. Additionally, it looks like when you pasted your configuration it lost some of the backslashes. To prevent this in the future, you can attach files directly to an issue by dragging and dropping them onto the issue editing box.

I'm going to close this issue since it is not relevant to this repository, but feel free to submit this problem to Loom issue tracker.
